=== romaasanovich/GRSU_SEM_4/2lap/file.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT myinterests (library,playlist,cars)>
<!ATTLIST myinterests
  xmlns CDATA #FIXED ''>

<!ELEMENT library (book)+>
<!ATTLIST library
  xmlns CDATA #FIXED ''>

<!ELEMENT playlist (sound)+>
<!ATTLIST playlist
  xmlns CDATA #FIXED ''>

<!ELEMENT cars (car)+>
<!ATTLIST cars
  xmlns CDATA #FIXED ''>

<!ELEMENT book (title,author,(binding|pages)+,priceinshoop)>
<!ATTLIST book
  xmlns CDATA #FIXED ''>

<!ELEMENT sound (artist,song,informationflowrate,durability,Released)>
<!ATTLIST sound
  xmlns CDATA #FIXED ''>

<!ELEMENT car (mark,model,yearofissue,enginecapacity,atype,
               maximumtorque)>
<!ATTLIST car
  xmlns CDATA #FIXED ''>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  xmlns CDATA #FIXED ''>

<!ELEMENT author (#PCDATA)>
<!ATTLIST author
  xmlns CDATA #FIXED ''>

<!ELEMENT binding (#PCDATA)>
<!ATTLIST binding
  xmlns CDATA #FIXED ''>

<!ELEMENT pages (#PCDATA)>
<!ATTLIST pages
  xmlns CDATA #FIXED ''>

<!ELEMENT priceinshoop (#PCDATA)>
<!ATTLIST priceinshoop
  xmlns CDATA #FIXED ''>

<!ELEMENT artist (#PCDATA)>
<!ATTLIST artist
  xmlns CDATA #FIXED ''>

<!ELEMENT song (#PCDATA)>
<!ATTLIST song
  xmlns CDATA #FIXED ''>

<!ELEMENT informationflowrate (#PCDATA)>
<!ATTLIST informationflowrate
  xmlns CDATA #FIXED ''>

<!ELEMENT durability (#PCDATA)>
<!ATTLIST durability
  xmlns CDATA #FIXED ''>

<!ELEMENT Released (#PCDATA)>
<!ATTLIST Released
  xmlns CDATA #FIXED ''>

<!ELEMENT mark (#PCDATA)>
<!ATTLIST mark
  xmlns CDATA #FIXED ''>

<!ELEMENT model (#PCDATA)>
<!ATTLIST model
  xmlns CDATA #FIXED ''>

<!ELEMENT yearofissue (#PCDATA)>
<!ATTLIST yearofissue
  xmlns CDATA #FIXED ''>

<!ELEMENT enginecapacity (#PCDATA)>
<!ATTLIST enginecapacity
  xmlns CDATA #FIXED ''>

<!ELEMENT atype (#PCDATA)>
<!ATTLIST atype
  xmlns CDATA #FIXED ''>

<!ELEMENT maximumtorque (#PCDATA)>
<!ATTLIST maximumtorque
  xmlns CDATA #FIXED ''>

=== romaasanovich/GRSU_SEM_4/2lap/code.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bookstoreandplaylist SYSTEM "file.dtd">


<myinterests>
<library>	
 <book>
    <title>The Master and Margarita</title>
    <author> Mikhail Bulgakov</author>
    <binding>Exclusive</binding>
    <pages> 250 pages</pages>
    <priceinshoop>110.20$</priceinshoop>
 </book>
 <book>
	<title>War and Peace</title>
	<author>Leo Tolstoy</author>
	<pages>1274 pages</pages>
	<binding>Exclusive</binding>
	<priceinshoop>250$</priceinshoop>
</book>	
<book>
	<title>The beauty and the Beast</title>
	<author>Gabriel Susanna Barbo de Villeneuve</author>
	<pages>320 pages </pages>
	<binding>Exclusive</binding>
	<priceinshoop>115$</priceinshoop>
</book>
	</library>
<playlist>
<sound>
    <artist>MOT</artist>
	<song>Great</song>
	<informationflowrate> 320 kbps</informationflowrate>
	<durability>3.33 sec</durability>
	<Released> 2015</Released>
</sound>
<sound>
    <artist>Eminem</artist>
	<song>Rap God</song>
	<informationflowrate> 320 kbps </informationflowrate>
	<durability>6.03 sec</durability>
	<Released> 2013</Released>
</sound>
<sound>
    <artist>dramma</artist>
	<song>Glide</song>
	<informationflowrate> 320 kbps </informationflowrate>
	<durability>3.40 sec</durability>
	<Released> 2014</Released>
</sound>
	</playlist>
<cars>
  <car>
	<mark>Audi</mark>
	<model>Q7 Res1</model>
	<yearofissue>2010</yearofissue>
	 <enginecapacity> 5999 см³</enginecapacity>
	  <atype>SUV</atype>
	  <maximumtorque> 1000 n*m</maximumtorque>
  </car>
	<car>
	<mark>BMW</mark>
	<model>M760Li xDrive (G12)</model>
	<yearofissue>2017</yearofissue>
	 <enginecapacity> 6592 см³</enginecapacity>
	  <atype>sedan</atype>
	  <maximumtorque> 800 n*m</maximumtorque>
  </car>
	<car>
	<mark>Mercedes</mark>
	<model>	AMG S 65 Coupe</model>
	<yearofissue>2018</yearofissue>
	 <enginecapacity> 6000 см³</enginecapacity>
	  <atype>sprot coupe</atype>
	  <maximumtorque> 1000 n*m</maximumtorque>
  </car>
</cars>
</myinterests>
